version: '3.8'

services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    restart: unless-stopped
    ports:
      - "${WAHA_PORT:-3000}:3000"
    environment:
      - WAHA_PRINT_QR=true
      - WAHA_LOG_LEVEL=${WAHA_LOG_LEVEL:-info}
    volumes:
      - waha_data:/app/.waha
    networks:
      - waha-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL:-http://localhost:5678}
      - GENERIC_TIMEZONE=${CRON_TZ:-America/Cuiaba}
      - TZ=${CRON_TZ:-America/Cuiaba}
      # Supabase credentials
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE=${SUPABASE_SERVICE_ROLE}
      # WAHA connection
      - WAHA_BASE_URL=${WAHA_BASE_URL:-http://waha:3000}
      - WAHA_SEND_TEXT_PATH=${WAHA_SEND_TEXT_PATH:-/api/sendText}
      # Optional SMTP
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n:/backup
    networks:
      - waha-network
    depends_on:
      - waha

  # postgres:
  #   image: postgres:15-alpine
  #   container_name: postgres-local
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB:-n8n}
  #     - POSTGRES_USER=${POSTGRES_USER:-n8n}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - waha-network
  #   ports:
  #     - "5432:5432"

volumes:
  waha_data:
    driver: local
  n8n_data:
    driver: local
  # postgres_data:
  #   driver: local

networks:
  waha-network:
    driver: bridge
